CREATE TABLE `SUPPLIERS` (
	`SUPPLIER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`SUPPLIER_NAME` varchar(10) NOT NULL AUTO_INCREMENT,
	`SUPPLIER_ADDRESS_ID` numeric(10) NOT NULL,
	`EMAIL_ADDRESS` TEXT(10) NOT NULL,
	`PHONE_NUMBER` INT(10) NOT NULL,
	`ALTERNATE_PHONE_NUMBER` INT(10),
	PRIMARY KEY (`SUPPLIER_ID`)
);

CREATE TABLE `PRODUCTS` (
	`PRODUCT_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`PRODUCT_CODE` varchar(100) NOT NULL,
	`PRODUCT_NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`PRODUCT_ID`)
);

CREATE TABLE `CARRIERS` (
	`CARRIER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`CARRIER_NAME` varchar(100) NOT NULL,
	`SHIPPING_CHARGES` DECIMAL(100),
	`CARRIER_ADDRESS_ID` DECIMAL(100) NOT NULL,
	PRIMARY KEY (`CARRIER_ID`)
);

CREATE TABLE `DISTRIBUTION_CENTER` (
	`DISTRIBUTION_CENTER_ID` numeric NOT NULL AUTO_INCREMENT,
	`DISTRIBUTION_CENTER_NAME` varchar(100) NOT NULL,
	`DISTRIBUTION_CENTER_ADDRESS_ID` numeric(100) NOT NULL,
	PRIMARY KEY (`DISTRIBUTION_CENTER_ID`)
);

CREATE TABLE `ORDERS` (
	`ORDER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`ORDER_DATE` DATETIME(10) NOT NULL,
	`ORDER_STATUS` varchar(10) NOT NULL,
	`CUSTOMER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`ORDER_AMOUNT` double(10) NOT NULL,
	`ORDER_DISCOUNT` double(10),
	`CARRIER_ID` numeric(10) NOT NULL,
	`DISTRIBUTION_CENTER_ID` numeric(10) NOT NULL,
	PRIMARY KEY (`ORDER_ID`)
);

CREATE TABLE `ORDER_ITEMS` (
	`ORDER_ITEM_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`ORDER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`BATCH_NUMBER` double(5) NOT NULL,
	`PRODUCT_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`ITEM_QUANTITY` INT(5) NOT NULL,
	`ITEM_PRICE` double(5) NOT NULL,
	`DISCOUNT_AMOUNT` double(5),
	PRIMARY KEY (`ORDER_ITEM_ID`)
);

CREATE TABLE `INVENTORY` (
	`INVENTORY_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`BATCH_NUMBER` numeric(10) NOT NULL UNIQUE,
	`BATCH_DATE` DATE(10) NOT NULL,
	`SUPPLIER_ID` numeric(10) NOT NULL,
	`PRODUCT_ID` numeric(10) NOT NULL,
	`MFG_DATE` DATE(10) NOT NULL,
	`EXP_DATE` DATE(10) NOT NULL,
	`QUANTITY` INT(10) NOT NULL,
	`UNIT_PURCHASE_PRICE` double(10) NOT NULL,
	`UNIT_SELL_PRICE` double(10) NOT NULL,
	PRIMARY KEY (`INVENTORY_ID`)
);

CREATE TABLE `CUSTOMERS` (
	`CUSTOMER_ID` numeric(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(100) NOT NULL,
	`GENDER` char(1) NOT NULL,
	`DOB` year(100) NOT NULL,
	`JOINING_DATE` year(100) NOT NULL,
	`EMAIL_ADDRESS` mediumtext(20),
	`PHONE_NUMBER` INT(10),
	`ALTERNATE_PHONE_NUMBER` INT(10),
	`NATIONALITY` varchar(20),
	`IDENTITY_CARD_TYPE` varchar(20) DEFAULT 'AADHAR',
	`IDENTITY_CARD_NUMBER` varchar(20),
	PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE `ADDRESS` (
	`ADDRESS_ID` numeric NOT NULL AUTO_INCREMENT,
	`ADDRESS_TYPE` varchar(30) NOT NULL DEFAULT 'HOME',
	`ADDRESS_LINE1` varchar(100) NOT NULL,
	`ADDRESS_LINE2` varchar(100) NOT NULL,
	`ADDRESS_LINE3` varchar(100) NOT NULL,
	`CITY` varchar(100) NOT NULL,
	`STATE` varchar(100) NOT NULL,
	`COUNTRY` varchar(100) NOT NULL,
	`PINCODE` int(100),
	PRIMARY KEY (`ADDRESS_ID`)
);

CREATE TABLE `CUSTOMER_ADDRESS` (
	`CUSTOMER_ADDRESS_ID` numeric NOT NULL AUTO_INCREMENT,
	`CUSTOMER_ID` numeric NOT NULL,
	`ADDRESS_TYPE` varchar(10) NOT NULL DEFAULT 'HOME',
	`ADDRESS_ID` numeric(10) NOT NULL DEFAULT 'HOME',
	PRIMARY KEY (`CUSTOMER_ADDRESS_ID`)
);

ALTER TABLE `SUPPLIERS` ADD CONSTRAINT `SUPPLIERS_fk0` FOREIGN KEY (`SUPPLIER_ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`);

ALTER TABLE `CARRIERS` ADD CONSTRAINT `CARRIERS_fk0` FOREIGN KEY (`CARRIER_ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`);

ALTER TABLE `DISTRIBUTION_CENTER` ADD CONSTRAINT `DISTRIBUTION_CENTER_fk0` FOREIGN KEY (`DISTRIBUTION_CENTER_ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`);

ALTER TABLE `ORDERS` ADD CONSTRAINT `ORDERS_fk0` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS`(`CUSTOMER_ID`);

ALTER TABLE `ORDERS` ADD CONSTRAINT `ORDERS_fk1` FOREIGN KEY (`CARRIER_ID`) REFERENCES `CARRIERS`(`CARRIER_ID`);

ALTER TABLE `ORDERS` ADD CONSTRAINT `ORDERS_fk2` FOREIGN KEY (`DISTRIBUTION_CENTER_ID`) REFERENCES `DISTRIBUTION_CENTER`(`DISTRIBUTION_CENTER_ID`);

ALTER TABLE `ORDER_ITEMS` ADD CONSTRAINT `ORDER_ITEMS_fk0` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS`(`ORDER_ID`);

ALTER TABLE `ORDER_ITEMS` ADD CONSTRAINT `ORDER_ITEMS_fk1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS`(`PRODUCT_ID`);

ALTER TABLE `INVENTORY` ADD CONSTRAINT `INVENTORY_fk0` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIERS`(`SUPPLIER_ID`);

ALTER TABLE `INVENTORY` ADD CONSTRAINT `INVENTORY_fk1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS`(`PRODUCT_ID`);

ALTER TABLE `CUSTOMER_ADDRESS` ADD CONSTRAINT `CUSTOMER_ADDRESS_fk0` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS`(`CUSTOMER_ID`);

ALTER TABLE `CUSTOMER_ADDRESS` ADD CONSTRAINT `CUSTOMER_ADDRESS_fk1` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`);

